#ifndef can_move_return_values_header
#define can_move_return_values_header

#define BASIC_CHECK 1
#define BASIC_INVALID_MOVE 2
#define BASIC_NO_PIECE 3
#define BASIC_WRONG_COLOR 4
#define BISHOP_BLOCKED 101
#define BISHOP_COLOR 102
#define BISHOP_INVALID 103
#define CASTLING_CHECK 201
#define CASTLING_COLOR 202
#define CASTLING_KING_MOVED 203
#define CASTLING_NOT_KING 204
#define CASTLING_NOT_ROOK 205
#define CASTLING_NOT_SAME_ROW 206
#define CASTLING_OCCUPIED 207
#define CASTLING_ROOK_MOVED 208
#define KING_COLOR 301;
#define KING_INVALID 302;
#define KNIGHT_COLOR 303;
#define KNIGHT_INVALID 304;
#define PASSANT_EXPIRED 401;
#define PASSANT_INVALID 402;
#define PASSANT_INVALID_LOC 403;
#define PASSANT_INVALID_MOVE 404;
#define PASSANT_NOT_PAWN_O 405;
#define PASSANT_NOT_PAWN_T 406;
#define PASSANT_WRONG_COLOR 407;
#define PAWN_BLOCKED 501;
#define PAWN_COLOR 502;
#define PAWN_FORWARD_EXPIRED 503;
#define PAWN_INVALID 504;
#define PAWN_NO_CAPTURE 505;
#define PAWN_PROMOTION 506;
#define PROMOTE_BLOCKED 601;
#define PROMOTE_COLOR 602;
#define PROMOTE_INVALID 603;
#define PROMOTE_NO 604;
#define PROMOTE_NO_CAPTURE 605;
#define PROMOTE_PAWN 606;
#define QUEEN_BLOCKED 701;
#define QUEEN_COLOR 702;
#define QUEEN_INVALID 703;
#define ROOK_BLOCKED 801;
#define ROOK_COLOR 802;
#define ROOK_INVALID 803;
#define BASIC_TERRIBLE 99

#endif
